[tool.poetry]
name = "quant-nb"
version = "0.1.0"
description = ""
authors = ["Alpha <piotr@piotryordanov.com>"]
readme = "README.md"
packages = [{include = "quant"}]

[tool.poetry.dependencies]
python = "^3.11"
numba = "^0.57.0"
numpy = "^1.24.3"
pandas = "^2.0.1"
ta-lib = "^0.4.26"
quantstats = "^0.0.59"
matplotlib = "^3.7.1"
pyarrow = "^12.0.0"
mplfinance = "^0.12.9b7"
pandas-ta = "^0.3.14b0"
dask = {extras = ["distributed"], version = "^2023.5.0"}
tqdm = "^4.65.0"
pynvim = "^0.4.3"
python-binance = "^1.0.17"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
